[phases.setup]
nixPkgs = ['nodejs_18', 'yarn']

[phases.install]
cmd = 'yarn install --frozen-lockfile || yarn install'

[phases.build] 
cmd = 'yarn build'

[start]
cmd = 'yarn start'

[variables]
NODE_ENV = 'production'
